export const data = [
  {
    id: 1,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product1.jpg",
    productName: "Macbook Pro",
    sku: "PT001",
    category: "Computers",
    brand: "N/D",
    price: "150.00",
    unit: "PC",
    qty: "100.00",
    createdBy: "Admin",
    action: "button",
  },
  {
    id: 2,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product2.jpg",
    productName: "AAaaa",
    sku: "988",
    category: "obc",
    brand: "man",
    price: "150",
    unit: "8",
    qty: "unknown",
    createdBy: "admin",
    action: "button",
  },
  {
    id: 3,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product3.jpg",
    productName: "zzzz",
    sku: "198",
    category: "oc",
    brand: "mn",
    price: "150",
    unit: "8",
    qty: "unkown",
    createdBy: "admin",
    action: "button",
  },
  {
    id: 4,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product4.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 5,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product5.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 6,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product6.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 7,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product7.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 8,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product8.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 9,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product9.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 10,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product11.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
  {
    id: 11,
    image:
      "https://dreamspos.dreamguystech.com/html/template/assets/img/product/product17.jpg",
    productName: "wwwww",
    sku: "188",
    category: "bc",
    brand: "man",
    price: "50",
    unit: "8",
    qty: "known",
    createdBy: "admin",
    action: "utton",
  },
];
